services:
  - type: web
    name: Foodie_client
    env: node
    rootDir: my-app
    buildCommand: npm install && npm run build
    startCommand: npx serve dist
    autoDeployTrigger: commit
    plan: free

  - type: web
    name: Foodie_backend
    env: node
    rootDir: backend
    buildCommand: npm install && npm run build
    startCommand: npm start
    autoDeployTrigger: commit
    plan: free
